from pathlib import Path
from typing import Any, Dict

try:
    from scripts.experiment_io import read_json
except ModuleNotFoundError:
    from experiment_io import read_json


ACCURACY_RESULT_COLUMNS = [
    "task_id",
    "benchmark",
    "method_id",
    "setting",
    "seed",
    "dataset_format",
    "split_protocol",
    "leakage_warning",
    "num_test_samples",
    "vote_acc",
    "plurality_vote_acc",
    "strict_plurality_win_rate",
    "plurality_top_tie_rate",
    "majority_vote_acc",
    "weighted_vote_acc",
    "mean_individual_acc",
    "best_individual_acc",
    "per_agent_acc",
    "min_individual_acc",
    "bottom2_mean_acc",
    "bottom3_mean_acc",
    "individual_acc_std",
    "best_minus_worst_gap",
    "best_minus_bottom2_gap",
    "oracle_acc",
    "aggregation_gap",
    "oracle_minus_plurality_vote",
    "c2_minus_plurality_vote",
    "c3_minus_plurality_vote",
    "rescue_available_rate",
    "correct_disagreement_rate",
    "mean_useful_diversity",
    "mean_vote_margin",
    "mean_plurality_margin_votes",
    "mean_normalized_plurality_margin",
    "plurality_pivotal_fix_opportunity_rate",
    "plurality_pivotal_fix_rate",
    "plurality_pivotal_hold_rate",
    "mean_boundary_useful_diversity",
    "vote_tie_rate",
    "mean_pairwise_double_fault",
    "mean_pairwise_error_covariance",
    "same_wrong_pair_rate",
    "triple_joint_error_rate",
    "majority_failure_tail_rate",
    "coverage_depth_c1",
    "coverage_depth_c2",
    "coverage_depth_c3",
    "coverage_depth_c4",
    "coverage_depth_c5",
    "c1_minus_c2",
    "c2_minus_c3",
    "max_minority_rescue_share",
    "minority_rescue_hhi",
    "specialization_strength_final",
    "mean_specialization_strength",
    "initial_competence_probe_bottom2",
    "final_competence_probe_bottom2",
    "competence_probe_bottom2_gain",
    "initial_competence_probe_mean_acc",
    "final_competence_probe_mean_acc",
    "competence_probe_mean_acc_gain",
    "initial_competence_probe_c1",
    "final_competence_probe_c1",
    "competence_probe_c1_gain",
    "initial_competence_probe_c2",
    "final_competence_probe_c2",
    "competence_probe_c2_gain",
    "all_wrong_rate",
    "first_nonzero_specialization_epoch",
    "effective_specialization_epoch_count",
    "max_specialization_strength",
    "progressive_stage_exercised",
    "progressive_stage_not_exercised_reason",
    "depth1_guard_rejection_count",
    "method_version",
    "competence_schedule_version",
    "target_selector_version",
    "beam_policy_version",
    "tcs_candidate_policy_version",
    "mechanism_signature_version",
    "catastrophic_accuracy_guard_rejection_count",
    "soft_error_dependence_penalty_count",
    "soft_cycle_penalty_count",
    "soft_mechanism_shift_penalty_count",
    "exploration_candidate_count",
    "exploration_slot_occupancy_rate",
    "exploration_to_active_conversion_count",
    "distinct_final_mechanism_signature_count",
    "dominant_final_mechanism_signature_share",
    "mean_pairwise_mechanism_signature_distance",
    "mean_inter_agent_behavior_distance",
    "min_inter_agent_behavior_distance",
    "mean_inter_agent_mechanism_distance",
    "mean_intra_agent_lineage_drift",
    "max_intra_agent_lineage_drift",
    "stable_specialization_score",
    "uncommitted_agent_count",
    "provisional_agent_count",
    "committed_agent_count",
    "lineage_committed_but_not_exercised",
    "lineage_commit_count",
    "lineage_switch_attempt_count",
    "lineage_switch_commit_count",
    "lineage_switch_cancel_count",
    "peer_collapse_soft_count",
    "peer_collapse_hard_rejection_count",
    "joint_team_combination_count",
    "joint_team_feasible_count",
    "joint_team_quality_frontier_count",
    "joint_team_quality_floor_feasible_count",
    "joint_team_final_candidate_count",
    "joint_team_change_limit_rejection_count",
    "joint_team_fold_quality_rejection_count",
    "candidate_starvation_count",
    "mechanism_starvation_count",
    "search_branch_starvation_count",
    "refill_requirements_unmet_count",
    "probation_to_safe_conversion_count",
    "probation_expired_count",
    "joint_team_selected_diversity_score",
    "joint_team_selected_stability_score",
    "active_from_incumbent_count",
    "active_from_task_repair_niche_count",
    "active_from_mechanism_niche_count",
    "mechanism_niche_occupancy_rate",
    "task_repair_niche_occupancy_rate",
    "active_team_selector_version",
    "lineage_policy_version",
    "mechanism_distance_version",
    "candidate_refill_version",
    "archive_policy_version",
    "joint_quality_filter_version",
    "probe_stability_version",
    "parent_selection_version",
    "baseline_aggregation_gap",
    "oracle_preserving_gap_reduction",
    "top_capability_family_per_agent",
    "distinct_top_capability_family_count",
    "dominant_capability_family_share",
    "capability_family_hhi",
    "mean_pairwise_capability_profile_cosine",
    "prompt_overlength_rejection_count",
    "truncated_prompt_count",
    "correct_agent_count_0",
    "correct_agent_count_1",
    "correct_agent_count_2",
    "correct_agent_count_3",
    "correct_agent_count_4",
    "correct_agent_count_5",
    "mean_boundary_conditional_error",
    "mean_pivotal_fix_rate",
    "mean_pivotal_hold_rate",
    "shared_error_rescue_rate",
    "shared_error_creation_rate",
    "boundary_shared_error_net_gain",
    "dominant_wrong_cluster_size",
    "gold_vs_largest_wrong_margin",
    "aggregation_mode",
    "requested_aggregation_mode",
    "effective_aggregation_mode",
    "plurality_boundary_version",
    "solver_calls",
    "optimizer_calls",
    "evaluator_calls",
    "total_llm_calls",
    "prompt_tokens",
    "completion_tokens",
    "total_tokens",
    "estimated_cost",
    "latency_seconds",
    "run_dir",
]


def _latest_test_metrics(history: Any) -> Dict[str, Any]:
    if not isinstance(history, list):
        return {}
    for record in reversed(history):
        if isinstance(record, dict) and isinstance(record.get("test"), dict):
            return record["test"]
    return {}


def build_accuracy_result_row(
    *,
    run_dir: Path,
    task_id: str,
    benchmark: str,
    setting: str,
    seed: int,
    dataset_format: str,
    split_protocol: str = "",
    leakage_warning: bool = False,
) -> Dict[str, Any]:
    history = read_json(run_dir / "history.json") or []
    test = _latest_test_metrics(history)
    cost = read_json(run_dir / "cost_summary.json") or {}
    meta = read_json(run_dir / "run_meta.json") or {}
    return {
        "task_id": task_id,
        "benchmark": benchmark,
        "method_id": f"mad_{setting}",
        "setting": setting,
        "seed": int(seed),
        "dataset_format": dataset_format,
        "split_protocol": split_protocol,
        "leakage_warning": bool(leakage_warning),
        "num_test_samples": int(test.get("num_test_samples", test.get("size", 0)) or 0),
        "vote_acc": float(test.get("vote_acc", 0.0) or 0.0),
        "plurality_vote_acc": float(test.get("plurality_vote_acc", test.get("vote_acc", 0.0)) or 0.0),
        "majority_vote_acc": float(test.get("majority_vote_acc", test.get("vote_acc", 0.0)) or 0.0),
        "weighted_vote_acc": float(test.get("weighted_vote_acc", 0.0) or 0.0),
        "mean_individual_acc": float(test.get("mean_individual_acc", 0.0) or 0.0),
        "best_individual_acc": float(test.get("best_individual_acc", 0.0) or 0.0),
        "per_agent_acc": test.get("per_agent_acc", []),
        "oracle_acc": float(test.get("oracle_acc", 0.0) or 0.0),
        "aggregation_gap": float(test.get("aggregation_gap", 0.0) or 0.0),
        "rescue_available_rate": float(test.get("rescue_available_rate", 0.0) or 0.0),
        "correct_disagreement_rate": float(test.get("correct_disagreement_rate", 0.0) or 0.0),
        "mean_useful_diversity": float(test.get("mean_useful_diversity", 0.0) or 0.0),
        "mean_vote_margin": float(test.get("mean_vote_margin", -1.0) if test.get("mean_vote_margin") is not None else -1.0),
        "mean_boundary_useful_diversity": float(test.get("mean_boundary_useful_diversity", 0.0) or 0.0),
        "vote_tie_rate": float(test.get("vote_tie_rate", 0.0) or 0.0),
        **{
            key: float(test.get(key, 0.0) or 0.0)
            for key in (
                "mean_pairwise_double_fault", "mean_pairwise_error_covariance", "same_wrong_pair_rate",
                "triple_joint_error_rate", "majority_failure_tail_rate", "coverage_depth_c1",
                "coverage_depth_c2", "coverage_depth_c3", "coverage_depth_c4", "coverage_depth_c5",
                "mean_boundary_conditional_error", "mean_pivotal_fix_rate", "mean_pivotal_hold_rate",
                "shared_error_rescue_rate", "shared_error_creation_rate", "boundary_shared_error_net_gain",
                "dominant_wrong_cluster_size", "gold_vs_largest_wrong_margin",
                "min_individual_acc", "bottom2_mean_acc", "bottom3_mean_acc", "individual_acc_std",
                "best_minus_worst_gap", "best_minus_bottom2_gap", "c1_minus_c2", "c2_minus_c3",
                "max_minority_rescue_share", "minority_rescue_hhi", "specialization_strength_final",
                "mean_specialization_strength",
                "strict_plurality_win_rate", "plurality_top_tie_rate",
                "oracle_minus_plurality_vote", "c2_minus_plurality_vote", "c3_minus_plurality_vote",
                "mean_plurality_margin_votes", "mean_normalized_plurality_margin",
                "plurality_pivotal_fix_opportunity_rate", "plurality_pivotal_fix_rate",
                "plurality_pivotal_hold_rate",
                "initial_competence_probe_bottom2", "final_competence_probe_bottom2",
                "competence_probe_bottom2_gain", "initial_competence_probe_mean_acc",
                "final_competence_probe_mean_acc", "competence_probe_mean_acc_gain",
                "initial_competence_probe_c1", "final_competence_probe_c1", "competence_probe_c1_gain",
                "initial_competence_probe_c2", "final_competence_probe_c2", "competence_probe_c2_gain",
                "all_wrong_rate", "max_specialization_strength", "dominant_capability_family_share",
                "capability_family_hhi", "mean_pairwise_capability_profile_cosine",
                "exploration_slot_occupancy_rate", "dominant_final_mechanism_signature_share",
                "mean_pairwise_mechanism_signature_distance",
                "mean_inter_agent_behavior_distance", "min_inter_agent_behavior_distance",
                "mean_inter_agent_mechanism_distance", "mean_intra_agent_lineage_drift",
                "max_intra_agent_lineage_drift", "stable_specialization_score",
                "joint_team_selected_diversity_score", "joint_team_selected_stability_score",
                "mechanism_niche_occupancy_rate", "task_repair_niche_occupancy_rate",
                "baseline_aggregation_gap",
            )
        },
        **{key: int(test.get(key, 0) or 0) for key in (
            "prompt_overlength_rejection_count", "truncated_prompt_count",
            "correct_agent_count_0", "correct_agent_count_1", "correct_agent_count_2",
            "correct_agent_count_3", "correct_agent_count_4", "correct_agent_count_5",
            "effective_specialization_epoch_count", "depth1_guard_rejection_count",
            "distinct_top_capability_family_count",
            "catastrophic_accuracy_guard_rejection_count", "soft_error_dependence_penalty_count",
            "soft_cycle_penalty_count", "soft_mechanism_shift_penalty_count",
            "exploration_candidate_count", "exploration_to_active_conversion_count",
            "distinct_final_mechanism_signature_count",
            "uncommitted_agent_count", "provisional_agent_count", "committed_agent_count",
            "lineage_committed_but_not_exercised", "lineage_commit_count",
            "lineage_switch_attempt_count", "lineage_switch_commit_count",
            "lineage_switch_cancel_count", "peer_collapse_soft_count",
            "peer_collapse_hard_rejection_count", "joint_team_combination_count",
            "joint_team_feasible_count", "joint_team_quality_frontier_count",
            "joint_team_quality_floor_feasible_count", "joint_team_final_candidate_count",
            "joint_team_change_limit_rejection_count", "joint_team_fold_quality_rejection_count",
            "candidate_starvation_count", "mechanism_starvation_count",
            "search_branch_starvation_count", "refill_requirements_unmet_count",
            "probation_to_safe_conversion_count", "probation_expired_count",
            "active_from_incumbent_count", "active_from_task_repair_niche_count",
            "active_from_mechanism_niche_count",
        )},
        **{key: str(test.get(key, meta.get(key, "")) or "") for key in (
            "method_version", "competence_schedule_version", "target_selector_version",
            "beam_policy_version", "tcs_candidate_policy_version", "mechanism_signature_version",
            "active_team_selector_version", "lineage_policy_version", "mechanism_distance_version",
            "candidate_refill_version", "archive_policy_version", "joint_quality_filter_version",
            "probe_stability_version", "parent_selection_version",
        )},
        "first_nonzero_specialization_epoch": test.get("first_nonzero_specialization_epoch"),
        "progressive_stage_exercised": bool(test.get("progressive_stage_exercised", False)),
        "oracle_preserving_gap_reduction": bool(test.get("oracle_preserving_gap_reduction", False)),
        "progressive_stage_not_exercised_reason": str(test.get("progressive_stage_not_exercised_reason", "")),
        "top_capability_family_per_agent": test.get("top_capability_family_per_agent", []),
        "aggregation_mode": str(test.get("aggregation_mode", "")),
        "requested_aggregation_mode": str(test.get("requested_aggregation_mode", test.get("aggregation_mode", ""))),
        "effective_aggregation_mode": str(test.get("effective_aggregation_mode", "")),
        "plurality_boundary_version": str(test.get("plurality_boundary_version", "")),
        "solver_calls": int(cost.get("solver_calls", 0) or 0),
        "optimizer_calls": int(cost.get("optimizer_calls", 0) or 0),
        "evaluator_calls": int(cost.get("evaluator_calls", 0) or 0),
        "total_llm_calls": int(cost.get("total_llm_calls", 0) or 0),
        "prompt_tokens": int(cost.get("prompt_tokens", 0) or 0),
        "completion_tokens": int(cost.get("completion_tokens", 0) or 0),
        "total_tokens": int(cost.get("total_tokens", 0) or 0),
        "estimated_cost": float(cost.get("estimated_cost", 0.0) or 0.0),
        "latency_seconds": float(cost.get("latency_seconds", 0.0) or 0.0),
        "run_dir": str(run_dir),
    }


def cost_summary_schema_keys():
    return {
        "solver_calls",
        "optimizer_calls",
        "evaluator_calls",
        "total_llm_calls",
        "prompt_tokens",
        "completion_tokens",
        "total_tokens",
        "estimated_cost",
        "latency_seconds",
    }
